# Enable Auto Reload Thymeleaf
# ONLY FOR DEVELOPMENT

spring:
    # Templates reloading during development
    thymeleaf:
        prefix: file:src/main/resources/templates/
        cache: false

    # Static resources reloading during development
    resources:
      static-locations: file:src/main/resources/static/
      cache-period: 0

    datasource:
      username: root
      password: 123456
      #  docker container mysql start :
      # docker run --name mysql02  -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -d mysql:5.5 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      url: jdbc:mysql://192.168.0.101:3306/jdbc # to docker container mysql:5.5  # use ip addr to get ip
      driver-class-name: com.mysql.jdbc.Driver

    # localization resource
    messages:
      basename: i18n.login

